# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

targeting_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - platform_x_joint
    - platform_y_joint
    - platform_z_joint
    - platform_a_joint
    - platform_b_joint
    - platform_c_Joint
  gains:
    platform_x_joint: {p: 10.0, i: 0.1, d: 1.0}
    platform_y_joint: {p: 10.0, i: 0.1, d: 1.0}
    platform_z_joint: {p: 100.0, i: 0.1, d: 1.0}
    platform_a_joint: {p: 10.0, i: 0.1, d: 1.0}
    platform_b_joint: {p: 10.0, i: 0.1, d: 1.0}
    platform_c_Joint: {p: 10.0, i: 0.1, d: 1.0}

