controller_list:
  - name: fake_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - platform_x_joint
      - platform_y_joint
      - platform_z_joint
      - platform_a_joint
      - platform_b_joint
      - platform_c_Joint
initial: # Define initial robot poses per group
  #  - group: planning_group
  #    pose: home

  []
