controller_list:
  - name: pos_controllers
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - platform_x_joint
      - platform_y_joint
      - platform_z_joint
      - platform_a_joint
      - platform_b_joint
      - platform_c_Joint
